//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugando
    {
        public int Id { get; set; }
        public int JuegoId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Juego Juego { get; set; }
    }
}
