

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Persistencia.Database
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ModelosDBContainer : DbContext
{
    public ModelosDBContainer()
        : base("name=ModelosDBContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Usuario> UsuarioSet { get; set; }

    public virtual DbSet<Juego> JuegoSet { get; set; }

    public virtual DbSet<Puntaje> PuntajeSet { get; set; }

    public virtual DbSet<Pregunta> PreguntaSet { get; set; }

    public virtual DbSet<Respuesta> RespuestaSet { get; set; }

}

}

