//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelosDBContainer : DbContext
    {
        public ModelosDBContainer()
            : base("name=ModelosDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<Juego> JuegoSet { get; set; }
        public virtual DbSet<Puntaje> PuntajeSet { get; set; }
        public virtual DbSet<Pregunta> PreguntaSet { get; set; }
        public virtual DbSet<Respuesta> RespuestaSet { get; set; }
        public virtual DbSet<Jugando> JugandoSet { get; set; }
    }
}
