//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pregunta()
        {
            this.Respuestas = new HashSet<Respuesta>();
        }
    
        public int Id { get; set; }
        public string Mensaje { get; set; }
        public long Tiempo { get; set; }
        public long Puntos { get; set; }
        public string Video { get; set; }
        public string Imagen { get; set; }
        public bool Quiz { get; set; }
        public int JuegoId { get; set; }
        public Nullable<long> InicioVideo { get; set; }
        public Nullable<long> FinVideo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta> Respuestas { get; set; }
        public virtual Juego Juego { get; set; }
    }
}
