//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int Id { get; set; }
        public string Mensaje { get; set; }
        public bool Correcta { get; set; }
        public long VecesSeleccionada { get; set; }
        public int PreguntaId { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
    }
}
